name: experience_exchange_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.0
  firebase_database: ^6.0.0
  firebase_analytics: ^5.0.2
  firebase_auth: ^1.0.0
  google_sign_in:
  json_annotation: 3.1.1
  provider: ^4.3.3
  firebase_dynamic_links: ^0.5.1
  http: ^0.13.0
  cloud_firestore: ^1.0.4
  firebase_storage: ^8.0.3
  logger: ^0.9.4
  font_awesome_flutter: ^9.0.0
  flutter_datetime_picker: ^1.5.0
  image_picker: ^0.7.4
  circular_profile_avatar: ^2.0.0
  image_cropper: ^1.4.0
  firebase_messaging: ^10.0.0
  async: any
  url_launcher: ^6.0.4
  overlay_support: any
  flutter_local_notifications: any

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  json_serializable: 3.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
